spring:
  application:
    name: case-tecnico-itau
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:itau}:${MONGODB_PASSWORD:itau}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:itau}?replicaSet=${MONGODB_REPLICASET:rs0}
itau:
  properties:
    sms-url: sms-url
    email-url: email-url
    carta-url: carta-url